name: Bug report 🐛
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Create a report to help us improve

  - type: input
    id: module-version
    attributes:
      label: Version
      description: Which version of LSUClient did you encounter the problem with?
      placeholder: e.g. 1.3.2
    validations:
      required: true

  - type: input
    id: computer-model
    attributes:
      label: Computer Model
      description: What model of computer did you encounter the problem on?
      placeholder: Run `(Get-CimInstance CIM_ComputerSystem).Model` and paste the output here or refer to the sticker on the computer
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Problem
      description: Describe the bug or problem, what commands you were running, etc.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Optional: Add anything else about the problem here
      placeholder: You can paste screenshots, links, log files or console output here
    validations:
      required: false
