name: Run PSScriptAnalyzer

on: [push]

jobs:
  PSSA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install PSScriptAnalyzer Module
      run : |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module PSScriptAnalyzer -Scope CurrentUser -Repository PSGallery -Force
      shell: pwsh -Command "$ProgressPreference = 'SilentlyContinue'; & '{0}'"

    - name: Run PSScriptAnalyzer
      run : |
        Import-Module PSScriptAnalyzer
        Invoke-ScriptAnalyzer -Path '.\' -ReportSummary -ExcludeRule PSAvoidTrailingWhitespace
      shell: pwsh -Command "$ProgressPreference = 'SilentlyContinue'; & '{0}'"
