name: Run PSScriptAnalyzer

on: push

jobs:
  PSSA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install PSScriptAnalyzer Module
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Repository PSGallery -Force
        shell: pwsh -Command "$ProgressPreference = 'SilentlyContinue'; & '{0}'"

      - name: Run PSScriptAnalyzer
        run: |
          Import-Module PSScriptAnalyzer
          $PSSAResults = Invoke-ScriptAnalyzer -Path "$ENV:GITHUB_WORKSPACE" -ExcludeRule PSAvoidTrailingWhitespace -Recurse
          $SUMMARY    = ($PSSAResults | Group-Object -Property Severity -NoElement | Foreach-Object { "- $($_.Count) $($_.Name)" }) -join [Environment]::NewLine
          $DETAILS    = ($PSSAResults | Format-List | Out-String).Trim()
          $STRINGBODY = "PSScriptAnalyzer results as of this commit:

          $SUMMARY

          <details><summary>See details</summary>

          ``````
          $DETAILS
          ``````

          </details>
          " | ConvertTo-Json -Compress

          $BODY = '"body":{0}' -f $STRINGBODY
          Set-Content -LiteralPath 'COMMENTBODY.json' -Value "{$BODY}"
        shell: pwsh -Command "$ProgressPreference = 'SilentlyContinue'; & '{0}'"

      - name: Add commit comment
        run: |
          curl -sL --data @COMMENTBODY.json \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
