name: Run PSScriptAnalyzer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install PSScriptAnalyzer Module
      run : |
        pwsh -Command "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted"
        pwsh -Command "Install-Module -Name PSScriptAnalyzer -AcceptLicense -Confirm:\$false"

    - name: Run PSScriptAnalyzer
      run : |
        pwsh -Command "Import-Module PSScriptAnalyzer; Invoke-ScriptAnalyzer -Path '.\' -ReportSummary -ExcludeRule PSAvoidTrailingWhitespace"
