name: Run PSScriptAnalyzer

on: push

jobs:
  PSSA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install PSScriptAnalyzer Module
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Repository PSGallery -Force
        shell: pwsh -Command "$ProgressPreference = 'SilentlyContinue'; & '{0}'"

      - name: Print contents of GITHUB_WORKSPACE (location of repo files)
        run: |
          ls -la "$GITHUB_WORKSPACE"

      - name: Run PSScriptAnalyzer
        run: |
          Import-Module PSScriptAnalyzer
          $PSSAResults = Invoke-ScriptAnalyzer -Path "$ENV:GITHUB_WORKSPACE" -ExcludeRule PSAvoidTrailingWhitespace -Recurse
          $PSSAResults
          Write-Output ""
          $PSSAResults | Group-Object -Property Severity -NoElement | ConvertTo-Json -Compress | Set-Content -LiteralPath 'COMMENTBODY.json'
        shell: pwsh -Command "$ProgressPreference = 'SilentlyContinue'; & '{0}'"

      - name: Add commit comment
        run: |
          curl -sL --data @COMMENTBODY.json \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
