name: Run PSScriptAnalyzer

on: [push]

jobs:
  PSSA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install PSScriptAnalyzer Module
      run : |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module PSScriptAnalyzer -Scope AllUsers -Repository PSGallery
      shell: pwsh

    - name: Run PSScriptAnalyzer
      run : |
        Import-Module PSScriptAnalyzer
        Invoke-ScriptAnalyzer -Path '.\' -ReportSummary -ExcludeRule PSAvoidTrailingWhitespace"
      shell: pwsh
